name: Build and lint
on:
  push:
    paths:
      - 'linux-cachyos/PKGBUILD'
      - '.github/workflows/lint.yml'
  workflow_dispatch:

jobs:
  linux-cachyos-zfs-gcc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build (GCC)
      id: makepkg
      uses: CachyOS/pkgbuild-action@master
      with:
        envvars: "_build_zfs=y _use_auto_optimization= _cc_harder= _localmodcfg=y _localmodcfg_path=/github/workspace/modprobed.db"
        pkgdir: "linux-cachyos"
        namcapExcludeRules: "invalidstartdir"
        makepkgArgs: "--skipchecksums --skippgpcheck --noconfirm -s"
  linux-cachyos-zfs-llvm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build (LLVM)
      id: makepkg
      uses: CachyOS/pkgbuild-action@master
      with:
        envvars: "CI=1 _build_zfs=y _use_llvm_lto=thin _use_auto_optimization= _cc_harder= _localmodcfg=y _localmodcfg_path=/github/workspace/modprobed.db"
        pkgdir: "linux-cachyos"
        namcapExcludeRules: "invalidstartdir"
        makepkgArgs: "--skipchecksums --skippgpcheck --noconfirm -s"
