name: Build and lint
on:
  push:
  workflow_dispatch:
jobs:
  linux-cachyos-zfs-gcc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build (GCC)
      id: makepkg
      uses: ventureoo/pkgbuild-action@master
      with:
        envvars: "_build_zfs=y"
        pkgdir: "linux-cachyos"
        namcapDisable: 1
        makepkgArgs: "--skippgpcheck --noconfirm -s"
  linux-cachyos-zfs-llvm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build (LLVM)
      id: makepkg
      uses: ventureoo/pkgbuild-action@master
      with:
        envvars: "_build_zfs=y _use_llvm_lto=thin"
        pkgdir: "linux-cachyos"
        namcapDisable: 1
        makepkgArgs: "--skippgpcheck --noconfirm -s"
