name: PKGBUILD CI
on:
  workflow_dispatch:
jobs:
  pkgbuild:
    steps:
    runs-on: [self-hosted]
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Checkout
      uses: actions/checkout@v2.3.4
        run: |
         chmod +x ./script.sh
         ./script.sh
        shell: bash
